"""Tender document summarizer.

Upload a PDF downloaded from a government procurement portal, get back a
human-readable summary: contract amount, deadlines, key requirements,
and penalties. The LLM backend (Ollama / NVIDIA NIM / DeepSeek) can be
chosen in the web UI.
"""

from __future__ import annotations

import logging

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import HTMLResponse, JSONResponse, Response

from app.llm_client import LlmError, build_extraction_prompt, summarize
from app.pdf_reader import EmptyPdfError, extract_text
from app.schemas import SummaryResponse
from app.web_ui import INDEX_HTML

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("tender_summarizer")

app = FastAPI(
    title="Tender Document Summarizer",
    description="Extracts contract amount, deadlines, requirements and "
    "penalties from tender PDFs using an LLM.",
    version="0.2.0",
)

MAX_UPLOAD_BYTES = 20 * 1024 * 1024  # 20 MB


@app.get("/", response_class=HTMLResponse)
async def index() -> HTMLResponse:
    """Minimal drag-and-drop UI for manually trying the service.

    /docs (Swagger, auto-generated by FastAPI) already covers this need
    for API-first testing — this page just makes a demo faster to run
    for someone reviewing the project without wanting to use curl.
    """
    return HTMLResponse(content=INDEX_HTML)


@app.get("/health")
async def health() -> dict:
    return {"status": "ok"}


@app.get("/favicon.ico")
async def favicon() -> Response:
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">'
        '<rect width="32" height="32" rx="6" fill="#2563eb"/>'
        '<text x="16" y="23" font-size="20" font-weight="bold" '
        'text-anchor="middle" fill="white" font-family="system-ui">T</text>'
        '</svg>'
    )
    return Response(content=svg.encode(), media_type="image/svg+xml")


@app.post("/summarize", response_model=SummaryResponse)
async def summarize_tender(
    file: UploadFile = File(...),
    provider: str = Form(default="ollama"),
    model: str = Form(default=""),
    api_key: str = Form(default=""),
    base_url: str = Form(default=""),
    host: str = Form(default=""),
) -> SummaryResponse:
    if file.content_type not in ("application/pdf", "application/x-pdf"):
        raise HTTPException(
            status_code=400,
            detail=f"Expected a PDF file, got content-type={file.content_type!r}",
        )

    pdf_bytes = await file.read()
    if len(pdf_bytes) > MAX_UPLOAD_BYTES:
        raise HTTPException(status_code=413, detail="File too large (max 20 MB).")

    try:
        document_text = extract_text(pdf_bytes)
    except EmptyPdfError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    prompt = build_extraction_prompt()

    logger.info("summarize: provider=%s model=%s has_key=%s", provider, model or "(default)", bool(api_key))

    try:
        summary_text = await summarize(
            document_text,
            prompt,
            provider=provider,
            model=model or None,
            api_key=api_key or None,
            base_url=base_url or None,
            host=host or None,
        )
        logger.info("summarize: done, %d chars", len(summary_text))
    except LlmError as exc:
        logger.error("LLM summarization failed for %s: %s", file.filename, exc)
        raise HTTPException(status_code=502, detail=str(exc)) from exc

    return SummaryResponse(filename=file.filename or "unknown.pdf", summary=summary_text)


@app.exception_handler(Exception)
async def unhandled_exception_handler(_request, exc: Exception) -> JSONResponse:
    logger.exception("Unhandled error")
    return JSONResponse(status_code=500, content={"detail": "Internal server error"})
